documentation:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**/*
          - "**/*/README.md"
ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**/*
          - .platform/**/*

source:
  - changed-files:
      - any-glob-to-any-file:
          - src/**/*

test:
  - changed-files:
      - any-glob-to-any-file:
          - test/**/*
