apiVersion: aws.3sidedcube.com/v1alpha1
kind: App
metadata:
  name: example-app
spec:
  name: example-app
  region: eu-west-2
  environment: production
  accountID: 381491948780
  database:
    name: exampledb
    username: exampleuser
    engine: postgres
    version: "16.4"
    storage: 20
    class: db.t4g.micro
    multiAz: false
  service:
    cpu: "512"
    memory: "1024"
    port: 80
  dns:
    name: example-app.idp.3sidedcube.com
